Staging release (#1418)
* feat: propose styled-components

* chore: fix code style

* chore: fix lint issue

* [PFDA-2298] Deploy Challenges redesign to /challenges and remove /new_challenges route

* • Back to to_unsafe_h from unsafe_params because it would result in NoMethodError (undefined method `unsafe_params' for #<ActionController::Parameters:0x0000555e3d8a0868>):
• Fix more links to not use turbolinks 
• Resolved ‘Upcoming’ link for challenges not having any actions

* • ChallengeProposeForm now resets when user submits a proposal then returns
• CollapsibleMenu is now open by default, also added pointer cursor when mouse is over to suggest interactivity

* • Removed unused search string query for fetchChallenges

* [PFDA-2300] Experts Page Redesign

* • User logged in as the expert can access expert edit and dashboard pages
• Fixed blog preview not being displayed (N.B. it is stored as ‘_challenge’ in the meta column of the experts tables)
• Circle icon for small expert list

* .gitignore: yarn-error.log should be ignored not only in project root

* feat: add global styles

* Removed unnecessary path in experts api route

* Replaced params.to_unsafe_h for the unsafe_params method on ActionController

* fix: different queue names (#1370)

Co-authored-by: PT <ptater@dnanexus.com>

* PFDA-2242 - workflow diagram (#1329)

* - workflow diagram

Closes [PFDA-2242](https://jira.internal.dnanexus.com/browse/PFDA-2242)

* - updates in workflow diagram drawing

* - update jest config

* - yarn lint & test fix

* - add titles to inputs and outputs
 - test fix
 - lint fix

* - clean code

Co-authored-by: Aleksei Ivanishchev <aivanishchev-cf@dnanexus.com>
Co-authored-by: Aleksandr Moroz <44093081+amorozdna@users.noreply.github.com>

* Remove reCaptcha for development, test and ui_test envs.

* Fix ActionController::RoutingError for bootstrap-select.js.map.

Fix this annoying routing error:

ActionController::RoutingError (No route matches [GET] "/assets/bootstrap-select/bootstrap-select.js.map"):
actionpack (6.0.3.3) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'

* PFDA-2337_2338 for https-apps yarn.lock (#1364)

* deps bump

* add: install snyk only in CI

* fix: ga typo

* add: install snyk in correct scope

* add: snyk to root deps

* fix: snyk correct local deps

* fix: test db env url

* fix: test only snyk

* fix: test worker

* fix: api tests

* PFDA-2291_New_executions_are_not_displayed_on_the_top (#1374)

* PFDA-2291_New_executions_are_not_displayed_on_the_top

 - update sort fields set for executions
 - update executions table

* - updates in sortable

* fix: deps reviewed

* fix: moved and excluded tests helper

* fix: import

* test: lerna bump

* fix: normal yarn.lock

* fix: snyk policy to handle currently unfixable issues

* fix: downgrade lerna

* Move some dev deps of client/package.json to deps.

This is needed for production deployment.

* Downgrade lerna.

* workaround for deploying client's yarn in production mode.

* chore: update webpack dev server entry file

* chore: fix eslint issue

* PFDA-2323_Publishing_of_sub-folders (#1380)

* PFDA-2323_Publishing_of_sub-folders

 - update folder serializer links
 - add folder spec
 - update guard folders to be watched

* - pronto fix

* - update user_file publish link usage

* - add rspec for user_file publish link usage

* - add rspec fix

* fix: deps reviewed

* test: lerna bump

* fix: downgrade lerna

* Move some dev deps of client/package.json to deps.

This is needed for production deployment.

* Downgrade lerna.

* Add missed packages to client/package.json.

* Adjust apps:transfer task.

* Fix/remove lerna (#1386)

* add: removed lerna

* add: production-build yarn lock

* fix: api deps

* Fix missed packages after rebasing in client/package.json.

* Pfda 2295 create new folder alerts issues (#1391)

* PFDA-2295_Create_new_folder_alerts_issues

 - update create_folder render data
 - update api call createFolder action

* - yarn lint fix

* Add invitationSearcher.

* Fix the most part of offences in admin/users_controller.rb.

* Remove unnecessary checks.

* Simplify before_action.

* Move new user provisioning under admin namespace.

* Fix tests for admin/provision_controller.rb.

* Add InvitationSearcher.

* Add new user provision method.

* Remove old user provisioning related methods.

* Fix admin routes.

* setting search autocomplete [WIP]

* Refactor provision_users method.

* add anf remove invitations

* styles for search autocomplete

* search done

* render table without styling

* styled table

* Add organize and participate intents to invitation search.

* Remove unused .keep file.

* Fix routes.

* styling table

* Remove unnecessary USER_PARAMS const.

* provison users

* Some markup fixes.

* Fix error message.

* Add 'exclude' param to InvitationSearcher.

* Add browse action to Admin::ProvisionController.

* Update routing.

* Update before_actions.

* Fix partial path.

* Fix JS for invitations.

* Add exclude to search invitations.

* Rename variable.

* browse modal

* Fix exclude param.

* getting grid by ajax

* Refactor InvitationSearcher.

* Add datatables lib.

* Move browse response to JSON.

* Remove unused template.

* installing datatable

* implementing dataTable

* using select and countries for 1st table

* add invitation to table from dataDatable

* Update country information.

* country name ui fix

* Render errors and warnings on user's bulk provision.

* handling errors and warnings

* Remove warnings.

* Remove warnings from frontend.

* Move error message to locale/en.yml.

* issue 1.1

* issue 1.2

* Validate user's email.

* 1.6 fix

* 1.7

* issue 1.3

* Add InvitationSerializer.

* Add yardoc for Admin/InvitationsController.

* Fix HTTP verbs in yardoc.

* limit invitations

* rename button

* fix

* fix 3.1

* issue 3.1 fix and 2.2 fixed in prev

* issue 2.1.

* Add yardoc for Naming.

* Add yardoc to Admin/UsersController.

* Remove unused actions.

* Add yardoc.

* Return some removed routes.

* Fix linter warns.

* Remove pending specs.

* Fix admin/apps_controller_spec.rb

* Remove not relevant InvitationsController spec.

* Fix ErrorProcessable spec.

* Update apps:transfer script.

* PFDA-1196: updates on bulk provisioning.

* Fix org name generation for user provision.

* Move sync methods from User model to the appropriate concerns.

* PFDA-2313_Execution_state_not_updated_in_Spaces (#1396)

* PFDA-2313_Execution_state_not_updated_in_Spaces

 - add sync jobs on render

* - pronto fix

* PFDA-2329_Title_of_renaming_modal

 - add title selection for renaming modal

* PFDA-2344, PFDA-2345, PFDA-2346: fix guest context.

* PFDA-2306_Comparator_setting_page_apps_should_have_home_links (#1402)

* PFDA-2306_Comparator_setting_page_apps_should_have_home_links

 - add home app path helper in a grid

* - PFDA-2336 fix: add option target to a grid

* PFDA-1657_Update_Welcome_to_precisionFDA_email_text

 - update guest_access_email

* Retrieve a guest user by /api/user endpoint.

* Pfda 1462 workflow readme is not displayed (#1406)

* PFDA-1462_Workflow_Readme_is_not_displayed

 - add readme tab
 - add Markdown to WF single page
 - update WF shape and serializers

* - yarn lint fix

* - rspec fix

* Add back btn to bulk provision page.

* Bulk provisioning: improve success message, allow ordering by requested_at.

* Bulk provisioning: improvements.

* Filter challenges by a time period: ended, current or upcoming.

* [PFDA-2027] Challenges time status buttons now filter the challenges list
            Sort challenges by end_at instead of start_at

* Trim org handle if its length exceeds maximum length.

* [PFDA-2272] Challenge Submissions and My Entries pages redesign
 - Replaces the tabs linked to in challenge details page
 - Submission creation, edit, and log pages are untouched

* Changed challenge tab routes from /challenge/123#submissions to /challenge/123/submissions and removed old Rails routes of /challenge/123/view/:tab

* PFDA-2363_Remove_Description_input_from_Rename_Asset_modal (#1413)

- exclude Description from assets rename modal

* Fix error loading Challenge submissions tab for an older challenge that does not have a review space attached to it (#1416)

(cherry picked from commit 09871fe20ba437778d86419858b802cd949c9e15)

* Add TMB challenge static page. (#1420)

(cherry picked from commit 45fbb568cf141ecaf98debea9d48acd267ccf9d7)

Co-authored-by: David Cech <dcech-cf@dnanexus.com>
Co-authored-by: Zai Chang <zchang-cf@dnanexus.com>
Co-authored-by: Zai Chang <zehao.chang@gmail.com>
Co-authored-by: Behalka <kbehalova@gmail.com>
Co-authored-by: Mr Ivanov <aivanov-cf@dnanexus.com>
Co-authored-by: Aleksei Ivanishchev <aivanishchev-cf@dnanexus.com>
Co-authored-by: Aleksandr Moroz <44093081+amorozdna@users.noreply.github.com>
Co-authored-by: Aleksandr Moroz <amoroz-cf@dnanexus.com>
Co-authored-by: Viktor Polotebnov <vpolotebnov-c@dnanexus.com>
Co-authored-by: Sergei Kutin <skutin-c@dnanexus.com>