• Back to to_unsafe_h from unsafe_params because it would result in NoMethodError (undefined method `unsafe_params' for #<ActionController::Parameters:0x0000555e3d8a0868>): • Fix more links to not use turbolinks • Resolved ‘Upcoming’ link for challenges not having any actions